version: '2'
services:
    worldwide-app:
        image: worldwide
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://worldwide-mysql:3306/worldwide?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    worldwide-mysql:
        extends:
            file: mysql.yml
            service: worldwide-mysql
